### ISSUE TITLE
SVM Kernel notebook has something with the libraries being imported. 

### ISSUE THREAD

**Issue by emisommer** [peteciank/abc_datascience_classification#1]
Hi @peteciank , I think there is a problem with this notebook where you explain the CVM Kernel, which is pointing to an incorrect Dataset as the error comes when trying to import the dataset. Comparing with the other notebooks, seems the link is different. 

Thank you for this wonderful contribution!
Emma

**Comment by peteciank** [comment]
Emma, I checked the dataset and indeed was different, I changed for the one prepared to be imported.

**Comment by emisommer** [comment]
> Emma, I checked the dataset and indeed was different, I changed for the one prepared to be imported.

Thank you!!!
